version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - serve
      - --development
      - "--config=/.governor.yaml"
    depends_on:
      - crdb
      - audit
    volumes:
      - type: volume
        source: audit-log
        target: /app-audit
        read_only: false
      - type: bind
        source: .governor-dev.yaml
        target: /.governor.yaml
        read_only: true
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - governor

  crdb:
    image: cockroachdb/cockroach:v22.2.14
    volumes:
      - db:/cockroach/cockroach-data
    command: start-single-node --insecure
    environment:
      #   sometimes crdb fails to start because of time drift - this helps to get it going
      - COCKROACH_RAFT_CLOSEDTS_ASSERTIONS_ENABLED=false
    ports:
      - "8080:8080"
      - "26257:26257"
    restart: unless-stopped
    networks:
      - governor

  hydra:
    image: oryd/hydra:v1.11.10
    ports:
      - "4444:4444" # Public Port
      - "4445:4445" # Admin Port
      - "5555:5555" # Port for hydra token user
    command: serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    depends_on:
      - hydra-migrate
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - ./hydra:/etc/config/hydra
    environment:
      - DSN=cockroach://root@crdb:26257/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: unless-stopped
    networks:
      - governor

  hydra-migrate:
    image: oryd/hydra:v1.11.10
    environment:
      - DSN=cockroach://root@crdb:26257/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    depends_on:
      - crdb
    volumes:
      - type: volume
        source: hydra-sqlite
        target: /var/lib/sqlite
        read_only: false
      - ./hydra:/etc/config/hydra
    restart: on-failure
    networks:
      - governor

  audit:
    image: ghcr.io/metal-toolbox/audittail:v0.8.0
    command: -f /app-audit/audit.log
    volumes:
      - type: volume
        source: audit-log
        target: /app-audit
        read_only: false
    restart: unless-stopped

  nats-server:
    image: nats:latest
    command:
      - -D
    ports:
      - "4222:4222"
    restart: unless-stopped
    networks:
      - governor

volumes:
  db:
  hydra-sqlite:
  audit-log:
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  governor:
